#ifndef ENV_H
#define ENV_H

#define FIREBASE_HOST "(YOUR_FIREBASE_HOST_HERE)"
#define FIREBASE_EMAIL "(YOUR_EMAIL_HERE)"
#define FIREBASE_PASSWORD "(YOUR_PASSWORD_HERE)"
#define FIREBASE_API_KEY "(YOUR_API_KEY_HERE)"

#endif
